### ISSUE TITLE
Support for anyhow/thiserror?

### ISSUE THREAD

**Issue by Boscop** [tismith/exitfailure#35]
Is there something like this that can be used with anyhow/thiserror? :)

**Comment by dtolnay** [comment]
What things from this crate are you looking for? Anyhow's error can already be used as the return type of main without an additional crate.

**Comment by Boscop** [comment]
@dtolnay This: 
> ExitDisplay<E>: a wrapper around E: std::fmt::Display to allow the error message from main to use Display and not Debug.

**Comment by dtolnay** [comment]
Anyhow already does that.

```rust
use anyhow::Result;

fn main() -> Result<()> {
    std::fs::read("/nonexistent")?;
    Ok(())
}
```

```console
Error: No such file or directory (os error 2)
```
